# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddBook.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddBook(object):
    def setupUi(self, AddBook):
        AddBook.setObjectName("AddBook")
        AddBook.resize(962, 499)
        AddBook.setMaximumSize(QtCore.QSize(16777215, 700))
        self.gridLayout_2 = QtWidgets.QGridLayout(AddBook)
        self.gridLayout_2.setContentsMargins(100, 200, 100, 100)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setVerticalSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(AddBook)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 758, 195))
        self.scrollAreaWidgetContents.setStyleSheet("QLineEdit, QLabel{\n"
"    margin-right:5px;\n"
"    margin-left:20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QDateEdit{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"    margin-right:5px;\n"
"    margin-left:20px;\n"
"}\n"
"")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.ClearButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClearButton.sizePolicy().hasHeightForWidth())
        self.ClearButton.setSizePolicy(sizePolicy)
        self.ClearButton.setStyleSheet("")
        self.ClearButton.setDefault(False)
        self.ClearButton.setFlat(False)
        self.ClearButton.setObjectName("ClearButton")
        self.gridLayout.addWidget(self.ClearButton, 7, 0, 1, 1)
        self.BookQuantityLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BookQuantityLineEdit.sizePolicy().hasHeightForWidth())
        self.BookQuantityLineEdit.setSizePolicy(sizePolicy)
        self.BookQuantityLineEdit.setStyleSheet("")
        self.BookQuantityLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.BookQuantityLineEdit.setObjectName("BookQuantityLineEdit")
        self.gridLayout.addWidget(self.BookQuantityLineEdit, 6, 2, 1, 1)
        self.BookIdLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BookIdLineEdit.sizePolicy().hasHeightForWidth())
        self.BookIdLineEdit.setSizePolicy(sizePolicy)
        self.BookIdLineEdit.setStyleSheet("")
        self.BookIdLineEdit.setObjectName("BookIdLineEdit")
        self.gridLayout.addWidget(self.BookIdLineEdit, 2, 0, 1, 1)
        self.BookPublisherLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BookPublisherLineEdit.sizePolicy().hasHeightForWidth())
        self.BookPublisherLineEdit.setSizePolicy(sizePolicy)
        self.BookPublisherLineEdit.setStyleSheet("")
        self.BookPublisherLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.BookPublisherLineEdit.setObjectName("BookPublisherLineEdit")
        self.gridLayout.addWidget(self.BookPublisherLineEdit, 6, 0, 1, 1)
        self.BookPublishedDate = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.BookPublishedDate.setStyleSheet("    color: rgb(255,255,255);\n"
"       background-color: rgb(35, 38, 41);\n"
"    border: 1px solid rgb(77, 208, 225);\n"
"    border-radius: 4px;\n"
"    padding: 8px 16px ;\n"
"    height: 18px;\n"
"    font-weight: bold;\n"
"    margin-right:5px;\n"
"    margin-left:20px;\n"
"    padding-left:20px;")
        self.BookPublishedDate.setCalendarPopup(True)
        self.BookPublishedDate.setObjectName("BookPublishedDate")
        self.gridLayout.addWidget(self.BookPublishedDate, 5, 2, 1, 1)
        self.BookTitleLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BookTitleLineEdit.sizePolicy().hasHeightForWidth())
        self.BookTitleLineEdit.setSizePolicy(sizePolicy)
        self.BookTitleLineEdit.setStyleSheet("")
        self.BookTitleLineEdit.setObjectName("BookTitleLineEdit")
        self.gridLayout.addWidget(self.BookTitleLineEdit, 3, 0, 1, 1)
        self.BookAuthorLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BookAuthorLineEdit.sizePolicy().hasHeightForWidth())
        self.BookAuthorLineEdit.setSizePolicy(sizePolicy)
        self.BookAuthorLineEdit.setStyleSheet("")
        self.BookAuthorLineEdit.setObjectName("BookAuthorLineEdit")
        self.gridLayout.addWidget(self.BookAuthorLineEdit, 5, 0, 1, 1)
        self.AddUserButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddUserButton.sizePolicy().hasHeightForWidth())
        self.AddUserButton.setSizePolicy(sizePolicy)
        self.AddUserButton.setStyleSheet("")
        self.AddUserButton.setDefault(False)
        self.AddUserButton.setFlat(False)
        self.AddUserButton.setObjectName("AddUserButton")
        self.gridLayout.addWidget(self.AddUserButton, 7, 2, 1, 1)
        self.BookEditionLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BookEditionLineEdit.sizePolicy().hasHeightForWidth())
        self.BookEditionLineEdit.setSizePolicy(sizePolicy)
        self.BookEditionLineEdit.setStyleSheet("")
        self.BookEditionLineEdit.setObjectName("BookEditionLineEdit")
        self.gridLayout.addWidget(self.BookEditionLineEdit, 2, 2, 1, 1)
        self.BookCategoryLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BookCategoryLineEdit.sizePolicy().hasHeightForWidth())
        self.BookCategoryLineEdit.setSizePolicy(sizePolicy)
        self.BookCategoryLineEdit.setStyleSheet("")
        self.BookCategoryLineEdit.setObjectName("BookCategoryLineEdit")
        self.gridLayout.addWidget(self.BookCategoryLineEdit, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 1, 1)

        self.retranslateUi(AddBook)
        QtCore.QMetaObject.connectSlotsByName(AddBook)

    def retranslateUi(self, AddBook):
        _translate = QtCore.QCoreApplication.translate
        AddBook.setWindowTitle(_translate("AddBook", "Form"))
        self.ClearButton.setText(_translate("AddBook", "Clear"))
        self.BookQuantityLineEdit.setPlaceholderText(_translate("AddBook", "Quantity"))
        self.BookIdLineEdit.setPlaceholderText(_translate("AddBook", "Book ID"))
        self.BookPublisherLineEdit.setPlaceholderText(_translate("AddBook", "Publisher"))
        self.BookTitleLineEdit.setPlaceholderText(_translate("AddBook", "Title"))
        self.BookAuthorLineEdit.setPlaceholderText(_translate("AddBook", "Author"))
        self.AddUserButton.setText(_translate("AddBook", "Add"))
        self.BookEditionLineEdit.setPlaceholderText(_translate("AddBook", "Edition"))
        self.BookCategoryLineEdit.setPlaceholderText(_translate("AddBook", "Category"))
        self.label.setText(_translate("AddBook", "Add Book"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddBook = QtWidgets.QWidget()
    ui = Ui_AddBook()
    ui.setupUi(AddBook)
    AddBook.show()
    sys.exit(app.exec_())
