# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Book.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Book(object):
    def setupUi(self, Book):
        Book.setObjectName("Book")
        Book.resize(250, 393)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Book.sizePolicy().hasHeightForWidth())
        Book.setSizePolicy(sizePolicy)
        Book.setStyleSheet("border-style:none;\n"
"background-color:rgb(53, 57, 68);")
        self.gridLayout = QtWidgets.QGridLayout(Book)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Book)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PhotoContainer = QtWidgets.QFrame(self.frame)
        self.PhotoContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PhotoContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PhotoContainer.setObjectName("PhotoContainer")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.PhotoContainer)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.BookPhoto = QtWidgets.QLabel(self.PhotoContainer)
        self.BookPhoto.setText("")
        self.BookPhoto.setPixmap(QtGui.QPixmap("Resources/Images/NoImageAvailable.png"))
        self.BookPhoto.setScaledContents(True)
        self.BookPhoto.setObjectName("BookPhoto")
        self.gridLayout_2.addWidget(self.BookPhoto, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.PhotoContainer)
        self.BookDetails = QtWidgets.QFrame(self.frame)
        self.BookDetails.setStyleSheet("QLabel{\n"
"    color: white;\n"
"    font: 10pt \"Maiandra GD\";\n"
"}")
        self.BookDetails.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BookDetails.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BookDetails.setObjectName("BookDetails")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.BookDetails)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.BookTitle = QtWidgets.QLabel(self.BookDetails)
        self.BookTitle.setObjectName("BookTitle")
        self.verticalLayout_2.addWidget(self.BookTitle)
        self.BookAuthor = QtWidgets.QLabel(self.BookDetails)
        self.BookAuthor.setObjectName("BookAuthor")
        self.verticalLayout_2.addWidget(self.BookAuthor)
        self.verticalLayout.addWidget(self.BookDetails, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ButtonContainer = QtWidgets.QFrame(self.frame)
        self.ButtonContainer.setStyleSheet("QPushButton{\n"
"    height: 30px;\n"
"    background-color:rgb(96, 116, 166);\n"
"    color:white;\n"
"    border-color:rgb(96, 116, 166);\n"
"    border-radius:15px;\n"
"    padding-left: 20px;\n"
"    padding-right:20px;\n"
"    font-size:20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(38, 42, 54);\n"
"}")
        self.ButtonContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ButtonContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonContainer.setObjectName("ButtonContainer")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ButtonContainer)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.BorrowButton = QtWidgets.QPushButton(self.ButtonContainer)
        self.BorrowButton.setStyleSheet("")
        self.BorrowButton.setObjectName("BorrowButton")
        self.gridLayout_3.addWidget(self.BorrowButton, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.ButtonContainer)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Book)
        QtCore.QMetaObject.connectSlotsByName(Book)

    def retranslateUi(self, Book):
        _translate = QtCore.QCoreApplication.translate
        Book.setWindowTitle(_translate("Book", "Form"))
        self.BookTitle.setText(_translate("Book", "Title"))
        self.BookAuthor.setText(_translate("Book", "Author"))
        self.BorrowButton.setText(_translate("Book", "Borrow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Book = QtWidgets.QWidget()
    ui = Ui_Book()
    ui.setupUi(Book)
    Book.show()
    sys.exit(app.exec_())
