# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IssuedBooks.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IssuedBooks(object):
    def setupUi(self, IssuedBooks):
        IssuedBooks.setObjectName("IssuedBooks")
        IssuedBooks.resize(788, 565)
        self.gridLayout = QtWidgets.QGridLayout(IssuedBooks)
        self.gridLayout.setContentsMargins(50, 50, 50, 50)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(IssuedBooks)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(IssuedBooks)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    color:white;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.ReturnButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ReturnButton.sizePolicy().hasHeightForWidth())
        self.ReturnButton.setSizePolicy(sizePolicy)
        self.ReturnButton.setStyleSheet("")
        self.ReturnButton.setObjectName("ReturnButton")
        self.horizontalLayout.addWidget(self.ReturnButton)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.tableWidget = QtWidgets.QTableWidget(IssuedBooks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(200)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget, 2, 0, 1, 1)

        self.retranslateUi(IssuedBooks)
        QtCore.QMetaObject.connectSlotsByName(IssuedBooks)

    def retranslateUi(self, IssuedBooks):
        _translate = QtCore.QCoreApplication.translate
        IssuedBooks.setWindowTitle(_translate("IssuedBooks", "Form"))
        self.label.setText(_translate("IssuedBooks", "Issued Books"))
        self.lineEdit.setPlaceholderText(_translate("IssuedBooks", "Search"))
        self.ReturnButton.setText(_translate("IssuedBooks", "Return Book"))
        self.tableWidget.setSortingEnabled(True)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IssuedBooks = QtWidgets.QWidget()
    ui = Ui_IssuedBooks()
    ui.setupUi(IssuedBooks)
    IssuedBooks.show()
    sys.exit(app.exec_())
