# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LibraryStudent.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Library(object):
    def setupUi(self, Library):
        Library.setObjectName("Library")
        Library.resize(877, 561)
        self.gridLayout_2 = QtWidgets.QGridLayout(Library)
        self.gridLayout_2.setContentsMargins(50, 50, 50, 50)
        self.gridLayout_2.setVerticalSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(Library)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SearchLineEdit = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchLineEdit.sizePolicy().hasHeightForWidth())
        self.SearchLineEdit.setSizePolicy(sizePolicy)
        self.SearchLineEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.SearchLineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.SearchLineEdit.setObjectName("SearchLineEdit")
        self.horizontalLayout.addWidget(self.SearchLineEdit)
        self.ComboBox = QtWidgets.QComboBox(self.frame)
        self.ComboBox.setObjectName("ComboBox")
        self.horizontalLayout.addWidget(self.ComboBox)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.scrollArea = QtWidgets.QScrollArea(Library)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 773, 374))
        self.scrollAreaWidgetContents.setStyleSheet("QWidget{\n"
"background-color: rgb(35, 38, 41)\n"
"}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(Library)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Library)
        QtCore.QMetaObject.connectSlotsByName(Library)

    def retranslateUi(self, Library):
        _translate = QtCore.QCoreApplication.translate
        Library.setWindowTitle(_translate("Library", "Form"))
        self.SearchLineEdit.setPlaceholderText(_translate("Library", "Search"))
        self.label.setText(_translate("Library", "Library"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Library = QtWidgets.QWidget()
    ui = Ui_Library()
    ui.setupUi(Library)
    Library.show()
    sys.exit(app.exec_())
