# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(811, 576)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Login.sizePolicy().hasHeightForWidth())
        Login.setSizePolicy(sizePolicy)
        Login.setStyleSheet("QWidget{\n"
"    border-style:none;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Login)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.LoginContainer = QtWidgets.QFrame(Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoginContainer.sizePolicy().hasHeightForWidth())
        self.LoginContainer.setSizePolicy(sizePolicy)
        self.LoginContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LoginContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LoginContainer.setObjectName("LoginContainer")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.LoginContainer)
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ColumnFrame = QtWidgets.QFrame(self.LoginContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColumnFrame.sizePolicy().hasHeightForWidth())
        self.ColumnFrame.setSizePolicy(sizePolicy)
        self.ColumnFrame.setStyleSheet("")
        self.ColumnFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ColumnFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ColumnFrame.setObjectName("ColumnFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.ColumnFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LogoFrame = QtWidgets.QFrame(self.ColumnFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogoFrame.sizePolicy().hasHeightForWidth())
        self.LogoFrame.setSizePolicy(sizePolicy)
        self.LogoFrame.setStyleSheet("background-color: rgb(53, 57, 68);")
        self.LogoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LogoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LogoFrame.setObjectName("LogoFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.LogoFrame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Logo = QtWidgets.QFrame(self.LogoFrame)
        self.Logo.setStyleSheet("QLabel{\n"
"    color: white;\n"
"    font: 25pt \"MS PGothic\";\n"
"}")
        self.Logo.setObjectName("Logo")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Logo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Icon = QtWidgets.QLabel(self.Logo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Icon.sizePolicy().hasHeightForWidth())
        self.Icon.setSizePolicy(sizePolicy)
        self.Icon.setText("")
        self.Icon.setPixmap(QtGui.QPixmap("Resources/Images/Library Inventory System.png"))
        self.Icon.setObjectName("Icon")
        self.verticalLayout.addWidget(self.Icon, 0, QtCore.Qt.AlignHCenter)
        self.Label = QtWidgets.QLabel(self.Logo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label.sizePolicy().hasHeightForWidth())
        self.Label.setSizePolicy(sizePolicy)
        self.Label.setObjectName("Label")
        self.verticalLayout.addWidget(self.Label, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addWidget(self.Logo, 0, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2.addWidget(self.LogoFrame)
        self.LoginFrame = QtWidgets.QFrame(self.ColumnFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoginFrame.sizePolicy().hasHeightForWidth())
        self.LoginFrame.setSizePolicy(sizePolicy)
        self.LoginFrame.setStyleSheet("background-color: rgb(38, 42, 54);")
        self.LoginFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LoginFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LoginFrame.setObjectName("LoginFrame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.LoginFrame)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.LoginForm = QtWidgets.QFrame(self.LoginFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoginForm.sizePolicy().hasHeightForWidth())
        self.LoginForm.setSizePolicy(sizePolicy)
        self.LoginForm.setStyleSheet("QLineEdit{\n"
"    background-color:rgb(96, 116, 166);\n"
"    border-color: rgb(96, 116, 166);\n"
"    border-radius:20px;\n"
"    color:white;\n"
"    height: 50px;\n"
"    width: 280px;\n"
"    margin-bottom: 10px;\n"
"    font-size:20px;\n"
"    textMargins: 10px;\n"
"    padding-left: 20px;\n"
"    padding-right:20px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    height: 50px;\n"
"    width: 280px;\n"
"    background-color:rgb(96, 116, 166);\n"
"    color:white;\n"
"    border-color:rgb(96, 116, 166);\n"
"    border-radius:20px;\n"
"    padding-left: 20px;\n"
"    padding-right:20px;\n"
"    font-size:20px;\n"
"}")
        self.LoginForm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LoginForm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LoginForm.setObjectName("LoginForm")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.LoginForm)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.UsernameLineEdit = QtWidgets.QLineEdit(self.LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsernameLineEdit.sizePolicy().hasHeightForWidth())
        self.UsernameLineEdit.setSizePolicy(sizePolicy)
        self.UsernameLineEdit.setStyleSheet("")
        self.UsernameLineEdit.setObjectName("UsernameLineEdit")
        self.verticalLayout_3.addWidget(self.UsernameLineEdit, 0, QtCore.Qt.AlignHCenter)
        self.PasswordLineEdit = QtWidgets.QLineEdit(self.LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PasswordLineEdit.sizePolicy().hasHeightForWidth())
        self.PasswordLineEdit.setSizePolicy(sizePolicy)
        self.PasswordLineEdit.setStyleSheet("")
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.verticalLayout_3.addWidget(self.PasswordLineEdit, 0, QtCore.Qt.AlignHCenter)
        self.LoginButton = QtWidgets.QPushButton(self.LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoginButton.sizePolicy().hasHeightForWidth())
        self.LoginButton.setSizePolicy(sizePolicy)
        self.LoginButton.setStyleSheet("")
        self.LoginButton.setDefault(False)
        self.LoginButton.setFlat(False)
        self.LoginButton.setObjectName("LoginButton")
        self.verticalLayout_3.addWidget(self.LoginButton, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_5.addWidget(self.LoginForm, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.LoginFrame)
        self.gridLayout_6.addWidget(self.ColumnFrame, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.LoginContainer, 0, 0, 1, 1)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.Label.setText(_translate("Login", "Library Inventory System"))
        self.UsernameLineEdit.setPlaceholderText(_translate("Login", "username"))
        self.PasswordLineEdit.setPlaceholderText(_translate("Login", "password"))
        self.LoginButton.setText(_translate("Login", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
