# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReturnedBooks.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReturnedBooks(object):
    def setupUi(self, ReturnedBooks):
        ReturnedBooks.setObjectName("ReturnedBooks")
        ReturnedBooks.resize(788, 565)
        self.gridLayout = QtWidgets.QGridLayout(ReturnedBooks)
        self.gridLayout.setContentsMargins(50, 50, 50, 50)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(ReturnedBooks)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    color:white;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.tableWidget = QtWidgets.QTableWidget(ReturnedBooks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(200)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(ReturnedBooks)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(ReturnedBooks)
        QtCore.QMetaObject.connectSlotsByName(ReturnedBooks)

    def retranslateUi(self, ReturnedBooks):
        _translate = QtCore.QCoreApplication.translate
        ReturnedBooks.setWindowTitle(_translate("ReturnedBooks", "Form"))
        self.lineEdit.setPlaceholderText(_translate("ReturnedBooks", "Search"))
        self.tableWidget.setSortingEnabled(True)
        self.label.setText(_translate("ReturnedBooks", "Returned Books"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReturnedBooks = QtWidgets.QWidget()
    ui = Ui_ReturnedBooks()
    ui.setupUi(ReturnedBooks)
    ReturnedBooks.show()
    sys.exit(app.exec_())
